"""add instructor model and link to cohorts

Revision ID: 2c57ac3bf854
Revises: b22ffcf7b09f
Create Date: 2025-11-27 02:32:18.445217

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c57ac3bf854"
down_revision: Union[str, Sequence[str], None] = "b22ffcf7b09f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instructors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("bio", sa.String(length=500), nullable=True),
        sa.Column("certification", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_instructors_id"), "instructors", ["id"], unique=False)
    op.add_column("cohorts", sa.Column("instructor_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "cohorts", "instructors", ["instructor_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cohorts", type_="foreignkey")
    op.drop_column("cohorts", "instructor_id")
    op.drop_index(op.f("ix_instructors_id"), table_name="instructors")
    op.drop_table("instructors")
    # ### end Alembic commands ###
