"""phase7_referral_dispatch_tables

Revision ID: 3f0166296a87
Revises: 9d48d853728b
Create Date: 2026-02-05 06:06:01.265745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f0166296a87'
down_revision: Union[str, Sequence[str], None] = '9d48d853728b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Display name: 'Wire Seattle'"),
    sa.Column('code', sa.String(length=30), nullable=False, comment="Unique code: 'WIRE_SEA_1'"),
    sa.Column('classification', sa.Enum('INSIDE_WIREPERSON', 'TRADESHOW', 'SEATTLE_SCHOOL', 'SOUND_COMM', 'MARINE', 'STOCKPERSON', 'LIGHT_FIXTURE', 'RESIDENTIAL', 'TECHNICIAN', 'UTILITY_WORKER', 'TERO_APPRENTICE', name='bookclassification'), nullable=False, comment='Job classification type'),
    sa.Column('book_number', sa.Integer(), nullable=False, comment='Book tier: 1=local members, 2=travelers, 3=other'),
    sa.Column('region', sa.Enum('SEATTLE', 'BREMERTON', 'PORT_ANGELES', name='bookregion'), nullable=False, comment='Geographic region - check marks are region-specific'),
    sa.Column('referral_start_time', sa.Time(), nullable=True, comment='Morning referral time (e.g., 08:30 for Inside Wire)'),
    sa.Column('re_sign_days', sa.Integer(), nullable=False, comment='Days before re-sign required (default 30)'),
    sa.Column('max_check_marks', sa.Integer(), nullable=False, comment='Check marks allowed before rolloff (3rd = rolled off)'),
    sa.Column('grace_period_days', sa.Integer(), nullable=True, comment='Grace period days after re-sign deadline'),
    sa.Column('max_days_on_book', sa.Integer(), nullable=True, comment='Max days before auto-rolloff (null = no limit)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this book is currently accepting registrations'),
    sa.Column('internet_bidding_enabled', sa.Boolean(), nullable=False, comment='Whether online bidding is allowed for this book'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_books_code'), 'referral_books', ['code'], unique=True)
    op.create_index(op.f('ix_referral_books_id'), 'referral_books', ['id'], unique=False)
    op.create_table('book_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False, comment='FK to member'),
    sa.Column('book_id', sa.Integer(), nullable=False, comment='FK to referral book'),
    sa.Column('registration_number', sa.Numeric(precision=10, scale=2), nullable=False, comment='APN - Applicant Priority Number (DECIMAL for FIFO ordering)'),
    sa.Column('registration_date', sa.DateTime(), nullable=False, comment='When member registered on book'),
    sa.Column('registration_method', sa.String(length=20), nullable=True, comment='How registered: in_person, email'),
    sa.Column('status', sa.Enum('REGISTERED', 'DISPATCHED', 'ROLLED_OFF', 'RESIGNED', 'EXEMPT', name='registrationstatus'), nullable=False, comment='Current registration status'),
    sa.Column('last_re_sign_date', sa.DateTime(), nullable=True, comment='Last time member re-signed'),
    sa.Column('re_sign_deadline', sa.DateTime(), nullable=True, comment='Deadline for next re-sign (30 days from last)'),
    sa.Column('check_marks', sa.Integer(), nullable=False, comment='Current check mark count (3 = rolled off)'),
    sa.Column('consecutive_missed_check_marks', sa.Integer(), nullable=False, comment='Consecutive missed check marks (for auto-rolloff)'),
    sa.Column('has_check_mark', sa.Boolean(), nullable=False, comment='Whether member currently has a check mark'),
    sa.Column('last_check_mark_date', sa.Date(), nullable=True, comment='Last date a check mark was recorded (max 1 per day)'),
    sa.Column('last_check_mark_at', sa.DateTime(), nullable=True, comment='Timestamp of last check mark'),
    sa.Column('no_check_mark_reason', sa.String(length=50), nullable=True, comment='Reason check mark was not given'),
    sa.Column('check_mark_restored_at', sa.DateTime(), nullable=True, comment='When check mark was restored by dispatcher'),
    sa.Column('short_call_restorations', sa.Integer(), nullable=False, comment='Times registration restored after short call (max 2)'),
    sa.Column('is_exempt', sa.Boolean(), nullable=False, comment='Whether member is exempt on this book'),
    sa.Column('exempt_reason', sa.Enum('MILITARY', 'UNION_BUSINESS', 'SALTING', 'MEDICAL', 'JURY_DUTY', 'UNDER_SCALE', 'TRAVELING', 'OTHER', name='exemptreason'), nullable=True, comment='Reason for exempt status'),
    sa.Column('exempt_start_date', sa.Date(), nullable=True, comment='When exempt status was granted'),
    sa.Column('exempt_end_date', sa.Date(), nullable=True, comment='When exempt status expires (max 6 months per rules)'),
    sa.Column('roll_off_date', sa.DateTime(), nullable=True, comment='When member was rolled off'),
    sa.Column('roll_off_reason', sa.Enum('CHECK_MARKS', 'QUIT', 'DISCHARGED', 'FAILED_RE_SIGN', 'NINETY_DAY_RULE', 'BID_REJECT_QUIT', 'EXPIRED', 'MANUAL', name='rolloffreason'), nullable=True, comment='Why member was rolled off'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes about this registration'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['referral_books.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'book_id', 'registration_number', name='uq_member_book_apn')
    )
    op.create_index('ix_book_queue_order', 'book_registrations', ['book_id', 'status', 'registration_number'], unique=False)
    op.create_index(op.f('ix_book_registrations_book_id'), 'book_registrations', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_registrations_id'), 'book_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_book_registrations_member_id'), 'book_registrations', ['member_id'], unique=False)
    op.create_index(op.f('ix_book_registrations_registration_number'), 'book_registrations', ['registration_number'], unique=False)
    op.create_table('labor_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False, comment='FK to employer organization'),
    sa.Column('employer_name', sa.String(length=200), nullable=True, comment='Denormalized employer name for display'),
    sa.Column('book_id', sa.Integer(), nullable=True, comment='FK to specific referral book'),
    sa.Column('contract_code', sa.String(length=30), nullable=True, comment='Contract code: WIREPERSON, SOUND_COMM, etc.'),
    sa.Column('job_class', sa.Enum('JRY_WIRE', 'SOUND', 'RESIDENTIAL', 'MARINE', 'STOCKPERSON', 'LIGHT_FIXTURE', 'TRADESHOW', 'TECHNICIAN', 'UTILITY_WORKER', name='jobclass'), nullable=True, comment='Job classification for this request'),
    sa.Column('classification', sa.Enum('INSIDE_WIREPERSON', 'TRADESHOW', 'SEATTLE_SCHOOL', 'SOUND_COMM', 'MARINE', 'STOCKPERSON', 'LIGHT_FIXTURE', 'RESIDENTIAL', 'TECHNICIAN', 'UTILITY_WORKER', 'TERO_APPRENTICE', name='bookclassification'), nullable=True, comment='Book classification type'),
    sa.Column('region', sa.Enum('SEATTLE', 'BREMERTON', 'PORT_ANGELES', name='bookregion'), nullable=True, comment='Geographic region for the request'),
    sa.Column('request_number', sa.String(length=20), nullable=True, comment='Internal tracking number'),
    sa.Column('request_date', sa.DateTime(), nullable=False, comment='When request was submitted'),
    sa.Column('workers_requested', sa.Integer(), nullable=False, comment='Number of workers requested'),
    sa.Column('workers_dispatched', sa.Integer(), nullable=False, comment='Number of workers already dispatched'),
    sa.Column('wage_rate', sa.Numeric(precision=10, scale=2), nullable=True, comment='Hourly wage rate'),
    sa.Column('worksite_name', sa.String(length=200), nullable=True, comment='Job site name'),
    sa.Column('worksite_address', sa.String(length=300), nullable=True, comment='Job site street address'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='City'),
    sa.Column('state', sa.String(length=2), nullable=False, comment='State (default WA)'),
    sa.Column('report_to_address', sa.String(length=300), nullable=True, comment='Where to report (may differ from worksite)'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='When the job starts'),
    sa.Column('start_time', sa.Time(), nullable=True, comment='Job start time'),
    sa.Column('estimated_duration_days', sa.Integer(), nullable=True, comment='Estimated job duration in business days'),
    sa.Column('is_short_call', sa.Boolean(), nullable=False, comment='Short call (<=10 business days)'),
    sa.Column('short_call_days', sa.Integer(), nullable=True, comment='If short call, number of days'),
    sa.Column('is_foreperson_by_name', sa.Boolean(), nullable=False, comment='Foreperson requested by name'),
    sa.Column('foreperson_member_id', sa.Integer(), nullable=True, comment='FK to requested foreperson'),
    sa.Column('generates_check_mark', sa.Boolean(), nullable=False, comment='Whether this request generates check marks'),
    sa.Column('no_check_mark_reason', sa.Enum('SPECIALTY', 'MOU_JOBSITE', 'EARLY_START', 'UNDER_SCALE', 'VARIOUS_LOCATION', 'SHORT_CALL', 'EMPLOYER_REJECTION', name='nocheckmarkreason'), nullable=True, comment='Why no check marks (if applicable)'),
    sa.Column('agreement_type', sa.Enum('STANDARD', 'PLA', 'CWA', 'TERO', name='agreementtype'), nullable=True, comment='PLA/CWA/TERO agreement type'),
    sa.Column('requirements', sa.Text(), nullable=True, comment='Job requirements (certifications, drug test, etc.)'),
    sa.Column('comments', sa.Text(), nullable=True, comment='Additional comments/instructions'),
    sa.Column('status', sa.Enum('OPEN', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', 'EXPIRED', name='laborrequeststatus'), nullable=False, comment='Current request status'),
    sa.Column('allows_online_bidding', sa.Boolean(), nullable=False, comment='Whether online bidding is enabled'),
    sa.Column('bidding_opens_at', sa.DateTime(), nullable=True, comment='When bidding opens (5:30 PM day before)'),
    sa.Column('bidding_closes_at', sa.DateTime(), nullable=True, comment='When bidding closes (7:00 AM day of)'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='User who created this request'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['referral_books.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employer_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['foreperson_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labor_requests_book_id'), 'labor_requests', ['book_id'], unique=False)
    op.create_index(op.f('ix_labor_requests_employer_id'), 'labor_requests', ['employer_id'], unique=False)
    op.create_index(op.f('ix_labor_requests_id'), 'labor_requests', ['id'], unique=False)
    op.create_index(op.f('ix_labor_requests_request_date'), 'labor_requests', ['request_date'], unique=False)
    op.create_index(op.f('ix_labor_requests_request_number'), 'labor_requests', ['request_number'], unique=True)
    op.create_table('registration_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True, comment='FK to registration (nullable for pre-registration actions)'),
    sa.Column('member_id', sa.Integer(), nullable=False, comment='FK to member'),
    sa.Column('book_id', sa.Integer(), nullable=True, comment='FK to book (nullable for cross-book actions)'),
    sa.Column('action', sa.Enum('REGISTER', 'RE_SIGN', 'RE_REGISTER', 'CHECK_MARK', 'CHECK_MARK_LOST', 'CHECK_MARK_RESTORED', 'ROLL_OFF', 'DISPATCH', 'RESIGN', 'RESTORE', 'EXEMPT_START', 'EXEMPT_END', 'POSITION_CHANGE', 'INTERNET_BID', 'BID_ACCEPT', 'BID_REJECT', 'MANUAL_EDIT', name='registrationaction'), nullable=False, comment='The action that occurred'),
    sa.Column('activity_date', sa.DateTime(), nullable=False, comment='When the action occurred'),
    sa.Column('previous_status', sa.Enum('REGISTERED', 'DISPATCHED', 'ROLLED_OFF', 'RESIGNED', 'EXEMPT', name='registrationstatus'), nullable=True, comment='Status before the action'),
    sa.Column('new_status', sa.Enum('REGISTERED', 'DISPATCHED', 'ROLLED_OFF', 'RESIGNED', 'EXEMPT', name='registrationstatus'), nullable=False, comment='Status after the action'),
    sa.Column('previous_position', sa.Integer(), nullable=True, comment='Queue position before action'),
    sa.Column('new_position', sa.Integer(), nullable=True, comment='Queue position after action'),
    sa.Column('labor_request_id', sa.Integer(), nullable=True, comment='FK to labor request if dispatch-related'),
    sa.Column('dispatch_id', sa.Integer(), nullable=True, comment='FK to dispatch if dispatch-related'),
    sa.Column('details', sa.Text(), nullable=True, comment='Human-readable description of the action'),
    sa.Column('reason', sa.String(length=200), nullable=True, comment='Reason for the action (rolloff reason, exempt reason, etc.)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('performed_by_id', sa.Integer(), nullable=False, comment='User who performed the action'),
    sa.Column('processor', sa.String(length=100), nullable=True, comment="Display name: 'SYSTEM', 'MEMBER VIA WEB', staff name"),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When this record was created'),
    sa.ForeignKeyConstraint(['book_id'], ['referral_books.id'], ),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], use_alter=True),
    sa.ForeignKeyConstraint(['labor_request_id'], ['labor_requests.id'], use_alter=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['book_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_activities_activity_date'), 'registration_activities', ['activity_date'], unique=False)
    op.create_index(op.f('ix_registration_activities_book_id'), 'registration_activities', ['book_id'], unique=False)
    op.create_index(op.f('ix_registration_activities_id'), 'registration_activities', ['id'], unique=False)
    op.create_index(op.f('ix_registration_activities_member_id'), 'registration_activities', ['member_id'], unique=False)
    op.create_index(op.f('ix_registration_activities_registration_id'), 'registration_activities', ['registration_id'], unique=False)
    op.create_table('job_bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('labor_request_id', sa.Integer(), nullable=False, comment='FK to labor request'),
    sa.Column('member_id', sa.Integer(), nullable=False, comment='FK to member who bid'),
    sa.Column('registration_id', sa.Integer(), nullable=True, comment="FK to member's registration on the book"),
    sa.Column('bid_submitted_at', sa.DateTime(), nullable=False, comment='When the bid was submitted'),
    sa.Column('bid_method', sa.String(length=20), nullable=True, comment='How bid was submitted: online, email, in_person'),
    sa.Column('queue_position_at_bid', sa.Integer(), nullable=True, comment="Member's queue position when they bid"),
    sa.Column('bid_status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'EXPIRED', name='bidstatus'), nullable=False, comment='Current bid status'),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='When bid was processed'),
    sa.Column('processed_by_id', sa.Integer(), nullable=True, comment='User who processed the bid'),
    sa.Column('was_dispatched', sa.Boolean(), nullable=False, comment='Whether this bid resulted in a dispatch'),
    sa.Column('dispatch_id', sa.Integer(), nullable=True, comment='FK to resulting dispatch (if any)'),
    sa.Column('rejected_by_member', sa.Boolean(), nullable=False, comment='Whether member rejected after accepting'),
    sa.Column('rejection_reason', sa.String(length=200), nullable=True, comment='Why bid was rejected'),
    sa.Column('rejection_date', sa.DateTime(), nullable=True, comment='When rejection occurred'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], use_alter=True),
    sa.ForeignKeyConstraint(['labor_request_id'], ['labor_requests.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['book_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_bids_bid_submitted_at'), 'job_bids', ['bid_submitted_at'], unique=False)
    op.create_index(op.f('ix_job_bids_id'), 'job_bids', ['id'], unique=False)
    op.create_index(op.f('ix_job_bids_labor_request_id'), 'job_bids', ['labor_request_id'], unique=False)
    op.create_index(op.f('ix_job_bids_member_id'), 'job_bids', ['member_id'], unique=False)
    op.create_index(op.f('ix_job_bids_registration_id'), 'job_bids', ['registration_id'], unique=False)
    op.create_table('dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('labor_request_id', sa.Integer(), nullable=False, comment='FK to labor request'),
    sa.Column('member_id', sa.Integer(), nullable=False, comment='FK to dispatched member'),
    sa.Column('registration_id', sa.Integer(), nullable=True, comment='FK to book registration at time of dispatch'),
    sa.Column('bid_id', sa.Integer(), nullable=True, comment='FK to bid if dispatched via online bidding'),
    sa.Column('employer_id', sa.Integer(), nullable=False, comment='FK to employer organization'),
    sa.Column('dispatch_date', sa.DateTime(), nullable=False, comment='When dispatch was made'),
    sa.Column('dispatch_method', sa.Enum('MORNING_REFERRAL', 'INTERNET_BID', 'EMAIL_BID', 'IN_PERSON', 'BY_NAME', 'EMERGENCY', name='dispatchmethod'), nullable=False, comment='How dispatch was made'),
    sa.Column('dispatch_type', sa.Enum('NORMAL', 'SHORT_CALL', 'EMERGENCY', name='dispatchtype'), nullable=False, comment='Type of dispatch (normal, short_call, emergency)'),
    sa.Column('dispatched_by_id', sa.Integer(), nullable=False, comment='User who made the dispatch'),
    sa.Column('job_class', sa.Enum('JRY_WIRE', 'SOUND', 'RESIDENTIAL', 'MARINE', 'STOCKPERSON', 'LIGHT_FIXTURE', 'TRADESHOW', 'TECHNICIAN', 'UTILITY_WORKER', name='jobclass'), nullable=True, comment='Job classification'),
    sa.Column('book_code', sa.String(length=30), nullable=True, comment='Referral book code at time of dispatch'),
    sa.Column('contract_code', sa.String(length=30), nullable=True, comment='Contract code'),
    sa.Column('worksite', sa.String(length=200), nullable=True, comment='Worksite name'),
    sa.Column('worksite_code', sa.String(length=30), nullable=True, comment='Worksite code'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='City'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Job start date'),
    sa.Column('start_time', sa.Time(), nullable=True, comment='Job start time'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='Expected job end date'),
    sa.Column('start_rate', sa.Numeric(precision=10, scale=2), nullable=True, comment='Hourly rate at start'),
    sa.Column('term_rate', sa.Numeric(precision=10, scale=2), nullable=True, comment='Hourly rate at termination'),
    sa.Column('dispatch_status', sa.Enum('DISPATCHED', 'CHECKED_IN', 'WORKING', 'COMPLETED', 'TERMINATED', 'REJECTED', 'NO_SHOW', name='dispatchstatus'), nullable=False, comment='Current dispatch status'),
    sa.Column('check_in_deadline', sa.DateTime(), nullable=True, comment='Deadline to check in with employer (3:00 PM)'),
    sa.Column('checked_in', sa.Boolean(), nullable=False, comment='Whether member checked in'),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True, comment='When member checked in'),
    sa.Column('is_short_call', sa.Boolean(), nullable=False, comment='Whether this is a short call (<=10 days)'),
    sa.Column('restore_to_book', sa.Boolean(), nullable=False, comment='Whether to restore position after short call'),
    sa.Column('restored_at', sa.DateTime(), nullable=True, comment='When position was restored'),
    sa.Column('term_date', sa.Date(), nullable=True, comment='Actual termination date'),
    sa.Column('term_reason', sa.Enum('RIF', 'QUIT', 'FIRED', 'LAID_OFF', 'SHORT_CALL_END', 'CONTRACT_END', 'NINETY_DAY_RULE', 'TURNAROUND', 'UNDER_SCALE', name='termreason'), nullable=True, comment='Termination reason'),
    sa.Column('term_comment', sa.String(length=200), nullable=True, comment='Additional termination details'),
    sa.Column('days_worked', sa.Integer(), nullable=True, comment='Total days worked'),
    sa.Column('hours_worked', sa.Numeric(precision=10, scale=2), nullable=True, comment='Total hours worked'),
    sa.Column('foreperson_restriction_until', sa.Date(), nullable=True, comment='Date until foreperson by-name restriction expires'),
    sa.Column('employment_id', sa.Integer(), nullable=True, comment='FK to created MemberEmployment record'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['job_bids.id'], ),
    sa.ForeignKeyConstraint(['dispatched_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employer_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['employment_id'], ['member_employments.id'], ),
    sa.ForeignKeyConstraint(['labor_request_id'], ['labor_requests.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['book_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatches_dispatch_date'), 'dispatches', ['dispatch_date'], unique=False)
    op.create_index(op.f('ix_dispatches_employer_id'), 'dispatches', ['employer_id'], unique=False)
    op.create_index(op.f('ix_dispatches_id'), 'dispatches', ['id'], unique=False)
    op.create_index(op.f('ix_dispatches_labor_request_id'), 'dispatches', ['labor_request_id'], unique=False)
    op.create_index(op.f('ix_dispatches_member_id'), 'dispatches', ['member_id'], unique=False)
    op.create_index(op.f('ix_dispatches_registration_id'), 'dispatches', ['registration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispatches_registration_id'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_member_id'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_labor_request_id'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_id'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_employer_id'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_dispatch_date'), table_name='dispatches')
    op.drop_table('dispatches')
    op.drop_index(op.f('ix_job_bids_registration_id'), table_name='job_bids')
    op.drop_index(op.f('ix_job_bids_member_id'), table_name='job_bids')
    op.drop_index(op.f('ix_job_bids_labor_request_id'), table_name='job_bids')
    op.drop_index(op.f('ix_job_bids_id'), table_name='job_bids')
    op.drop_index(op.f('ix_job_bids_bid_submitted_at'), table_name='job_bids')
    op.drop_table('job_bids')
    op.drop_index(op.f('ix_registration_activities_registration_id'), table_name='registration_activities')
    op.drop_index(op.f('ix_registration_activities_member_id'), table_name='registration_activities')
    op.drop_index(op.f('ix_registration_activities_id'), table_name='registration_activities')
    op.drop_index(op.f('ix_registration_activities_book_id'), table_name='registration_activities')
    op.drop_index(op.f('ix_registration_activities_activity_date'), table_name='registration_activities')
    op.drop_table('registration_activities')
    op.drop_index(op.f('ix_labor_requests_request_number'), table_name='labor_requests')
    op.drop_index(op.f('ix_labor_requests_request_date'), table_name='labor_requests')
    op.drop_index(op.f('ix_labor_requests_id'), table_name='labor_requests')
    op.drop_index(op.f('ix_labor_requests_employer_id'), table_name='labor_requests')
    op.drop_index(op.f('ix_labor_requests_book_id'), table_name='labor_requests')
    op.drop_table('labor_requests')
    op.drop_index(op.f('ix_book_registrations_registration_number'), table_name='book_registrations')
    op.drop_index(op.f('ix_book_registrations_member_id'), table_name='book_registrations')
    op.drop_index(op.f('ix_book_registrations_id'), table_name='book_registrations')
    op.drop_index(op.f('ix_book_registrations_book_id'), table_name='book_registrations')
    op.drop_index('ix_book_queue_order', table_name='book_registrations')
    op.drop_table('book_registrations')
    op.drop_index(op.f('ix_referral_books_id'), table_name='referral_books')
    op.drop_index(op.f('ix_referral_books_code'), table_name='referral_books')
    op.drop_table('referral_books')
    # ### end Alembic commands ###
