"""add hours_entries relationship to Instructor

Revision ID: 6945f65ab264
Revises: a9b228e41051
Create Date: 2025-11-27 03:37:27.779525

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "6945f65ab264"
down_revision: Union[str, Sequence[str], None] = "a9b228e41051"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
