"""add organization member audit models

Revision ID: 7967f77cdbb6
Revises: 3317e9b9b593
Create Date: 2026-01-27 03:54:57.220452

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7967f77cdbb6"
down_revision: Union[str, Sequence[str], None] = "3317e9b9b593"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("table_name", sa.String(length=100), nullable=False),
        sa.Column("record_id", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("old_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "changed_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("changed_by", sa.String(length=100), nullable=True),
        sa.Column(
            "changed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_record_id"), "audit_logs", ["record_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_table_name"), "audit_logs", ["table_name"], unique=False
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "org_type",
            sa.Enum(
                "EMPLOYER", "UNION", "TRAINING_PARTNER", "JATC", name="organizationtype"
            ),
            nullable=False,
        ),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("zip_code", sa.String(length=20), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column(
            "salting_score",
            sa.Enum(
                "HOSTILE",
                "RESISTANT",
                "NEUTRAL",
                "RECEPTIVE",
                "SUPPORTIVE",
                name="saltingscore",
            ),
            nullable=True,
        ),
        sa.Column("salting_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_id"), "organizations", ["id"], unique=False)
    op.create_index(
        op.f("ix_organizations_is_deleted"),
        "organizations",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organizations_name"), "organizations", ["name"], unique=False
    )
    op.create_table(
        "organization_contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_contacts_id"),
        "organization_contacts",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_contacts_is_deleted"),
        "organization_contacts",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_number", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("zip_code", sa.String(length=20), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("hire_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "SUSPENDED",
                "RETIRED",
                "DECEASED",
                name="memberstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "classification",
            sa.Enum(
                "APPRENTICE_1ST_YEAR",
                "APPRENTICE_2ND_YEAR",
                "APPRENTICE_3RD_YEAR",
                "APPRENTICE_4TH_YEAR",
                "APPRENTICE_5TH_YEAR",
                "JOURNEYMAN",
                "FOREMAN",
                "RETIREE",
                "HONORARY",
                name="memberclassification",
            ),
            nullable=False,
        ),
        sa.Column("student_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_members_id"), "members", ["id"], unique=False)
    op.create_index(
        op.f("ix_members_is_deleted"), "members", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_members_member_number"), "members", ["member_number"], unique=True
    )
    op.create_table(
        "member_employments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("job_title", sa.String(length=100), nullable=True),
        sa.Column("hourly_rate", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_member_employments_id"), "member_employments", ["id"], unique=False
    )
    op.drop_index(op.f("ix_file_attachment_record"), table_name="file_attachments")
    op.drop_index(op.f("ix_file_attachments_id"), table_name="file_attachments")
    op.drop_index(op.f("ix_file_attachments_is_deleted"), table_name="file_attachments")
    op.drop_index(op.f("ix_file_attachments_record_id"), table_name="file_attachments")
    op.drop_index(
        op.f("ix_file_attachments_record_type"), table_name="file_attachments"
    )
    op.drop_table("file_attachments")
    op.alter_column(
        "attendance",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "class_sessions",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "cohorts",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "credentials",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "expenses",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "grants",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "instructor_hours",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "instructors",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(op.f("instructors_email_key"), "instructors", type_="unique")
    op.alter_column(
        "jatc_applications",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_column("jatc_applications", "score")
    op.alter_column(
        "locations",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "students",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(op.f("students_email_key"), "students", type_="unique")
    op.alter_column(
        "tools_issued",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "tools_issued",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        op.f("students_email_key"),
        "students",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "students",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "locations",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.add_column(
        "jatc_applications",
        sa.Column(
            "score",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "jatc_applications",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        op.f("instructors_email_key"),
        "instructors",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "instructors",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "instructor_hours",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "grants",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "expenses",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "credentials",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "cohorts",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "class_sessions",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "attendance",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.create_table(
        "file_attachments",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "record_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("record_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "file_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "original_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "file_path", sa.VARCHAR(length=500), autoincrement=False, nullable=False
        ),
        sa.Column(
            "file_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("file_size", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "description", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "is_deleted",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("file_attachments_pkey")),
    )
    op.create_index(
        op.f("ix_file_attachments_record_type"),
        "file_attachments",
        ["record_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_file_attachments_record_id"),
        "file_attachments",
        ["record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_file_attachments_is_deleted"),
        "file_attachments",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_file_attachments_id"), "file_attachments", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_file_attachment_record"),
        "file_attachments",
        ["record_type", "record_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_member_employments_id"), table_name="member_employments")
    op.drop_table("member_employments")
    op.drop_index(op.f("ix_members_member_number"), table_name="members")
    op.drop_index(op.f("ix_members_is_deleted"), table_name="members")
    op.drop_index(op.f("ix_members_id"), table_name="members")
    op.drop_table("members")
    op.drop_index(
        op.f("ix_organization_contacts_is_deleted"), table_name="organization_contacts"
    )
    op.drop_index(
        op.f("ix_organization_contacts_id"), table_name="organization_contacts"
    )
    op.drop_table("organization_contacts")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_is_deleted"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_id"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_audit_logs_table_name"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_record_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
