"""add location model and cohort.location_id

Revision ID: 99b57fe87dfb
Revises: 2c57ac3bf854
Create Date: 2025-11-27 02:37:20.573926

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99b57fe87dfb"
down_revision: Union[str, Sequence[str], None] = "2c57ac3bf854"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("zip_code", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_locations_id"), "locations", ["id"], unique=False)
    op.add_column("cohorts", sa.Column("location_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "cohorts", "locations", ["location_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cohorts", type_="foreignkey")
    op.drop_column("cohorts", "location_id")
    op.drop_index(op.f("ix_locations_id"), table_name="locations")
    op.drop_table("locations")
    # ### end Alembic commands ###
