"""Add pre-apprenticeship training models

Revision ID: 9b75a876ef60
Revises: 381da02dc6f0
Create Date: 2026-01-28 09:15:54.675391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b75a876ef60'
down_revision: Union[str, Sequence[str], None] = '381da02dc6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create student_status_enum BEFORE adding the status column to students table
    # (Other enums are created automatically by create_table)
    student_status_enum = sa.Enum('APPLICANT', 'ENROLLED', 'ON_LEAVE', 'COMPLETED', 'DROPPED', 'DISMISSED', name='student_status_enum')
    student_status_enum.create(op.get_bind(), checkfirst=True)

    # Drop old attendance table FIRST to avoid constraint name conflicts
    op.drop_index(op.f('ix_attendance_class_session_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_is_deleted'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_status'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_table('attendance')

    # Create courses table
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_type', sa.Enum('CORE', 'ELECTIVE', 'REMEDIAL', 'ADVANCED', 'CERTIFICATION', name='course_type_enum'), nullable=False),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('passing_grade', sa.Float(), nullable=False),
    sa.Column('prerequisites', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.create_index(op.f('ix_courses_is_deleted'), 'courses', ['is_deleted'], unique=False)

    # Create new attendances table
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_session_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'EXCUSED', 'LATE', 'LEFT_EARLY', name='session_attendance_status_enum'), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'class_session_id', name='uq_student_session')
    )
    op.create_index(op.f('ix_attendances_class_session_id'), 'attendances', ['class_session_id'], unique=False)
    op.create_index(op.f('ix_attendances_status'), 'attendances', ['status'], unique=False)
    op.create_index(op.f('ix_attendances_student_id'), 'attendances', ['student_id'], unique=False)
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('cert_type', sa.Enum('OSHA_10', 'OSHA_30', 'FIRST_AID', 'CPR', 'FORKLIFT', 'AERIAL_LIFT', 'CONFINED_SPACE', 'HAZMAT', 'FLAGGER', 'ELECTRICAL_TRAINEE', 'OTHER', name='certification_type_enum'), nullable=False),
    sa.Column('custom_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', 'PENDING', name='certification_status_enum'), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('issuing_organization', sa.String(length=200), nullable=True),
    sa.Column('verified_by', sa.String(length=200), nullable=True),
    sa.Column('verification_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifications_cert_type'), 'certifications', ['cert_type'], unique=False)
    op.create_index(op.f('ix_certifications_status'), 'certifications', ['status'], unique=False)
    op.create_index(op.f('ix_certifications_student_id'), 'certifications', ['student_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('cohort', sa.String(length=50), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ENROLLED', 'COMPLETED', 'WITHDRAWN', 'FAILED', 'INCOMPLETE', name='course_enrollment_status_enum'), nullable=False),
    sa.Column('final_grade', sa.Float(), nullable=True),
    sa.Column('letter_grade', sa.String(length=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', 'cohort', name='uq_student_course_cohort')
    )
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_status'), 'enrollments', ['status'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('grade_type', sa.Enum('ASSIGNMENT', 'QUIZ', 'EXAM', 'PROJECT', 'PARTICIPATION', 'FINAL', name='grade_type_enum'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('points_earned', sa.Float(), nullable=False),
    sa.Column('points_possible', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('grade_date', sa.Date(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_course_id'), 'grades', ['course_id'], unique=False)
    op.create_index(op.f('ix_grades_student_id'), 'grades', ['student_id'], unique=False)

    # Modify class_sessions table
    op.add_column('class_sessions', sa.Column('course_id', sa.Integer(), nullable=False))
    op.add_column('class_sessions', sa.Column('session_date', sa.Date(), nullable=False))
    op.add_column('class_sessions', sa.Column('location', sa.String(length=200), nullable=True))
    op.add_column('class_sessions', sa.Column('room', sa.String(length=50), nullable=True))
    op.add_column('class_sessions', sa.Column('instructor_name', sa.String(length=200), nullable=True))
    op.add_column('class_sessions', sa.Column('is_cancelled', sa.Boolean(), nullable=False))
    op.add_column('class_sessions', sa.Column('cancellation_reason', sa.String(length=200), nullable=True))
    op.alter_column('class_sessions', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('class_sessions', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('class_sessions', 'topic',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index(op.f('ix_class_session_date_cohort'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_cohort_id'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_date'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_id'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_instructor_id'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_is_deleted'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_location_id'), table_name='class_sessions')
    op.create_index(op.f('ix_class_sessions_course_id'), 'class_sessions', ['course_id'], unique=False)
    op.create_index(op.f('ix_class_sessions_session_date'), 'class_sessions', ['session_date'], unique=False)
    op.drop_constraint(op.f('class_sessions_location_id_fkey'), 'class_sessions', type_='foreignkey')
    op.drop_constraint(op.f('class_sessions_instructor_id_fkey'), 'class_sessions', type_='foreignkey')
    op.drop_constraint(op.f('class_sessions_cohort_id_fkey'), 'class_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'class_sessions', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_column('class_sessions', 'deleted_at')
    op.drop_column('class_sessions', 'location_id')
    op.drop_column('class_sessions', 'is_deleted')
    op.drop_column('class_sessions', 'date')
    op.drop_column('class_sessions', 'cohort_id')
    op.drop_column('class_sessions', 'instructor_id')
    op.drop_constraint(op.f('members_student_id_fkey'), 'members', type_='foreignkey')
    op.drop_column('members', 'student_id')
    op.add_column('students', sa.Column('member_id', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('student_number', sa.String(length=20), nullable=False))
    op.add_column('students', sa.Column('status', sa.Enum('APPLICANT', 'ENROLLED', 'ON_LEAVE', 'COMPLETED', 'DROPPED', 'DISMISSED', name='student_status_enum'), nullable=False))
    op.add_column('students', sa.Column('application_date', sa.Date(), nullable=False))
    op.add_column('students', sa.Column('enrollment_date', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('expected_completion_date', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('actual_completion_date', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('cohort', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('students', 'emergency_contact_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('students', 'emergency_contact_phone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_student_city_state'), table_name='students')
    op.drop_index(op.f('ix_student_name'), table_name='students')
    op.drop_index(op.f('ix_students_cohort_id'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.create_index(op.f('ix_students_member_id'), 'students', ['member_id'], unique=True)
    op.create_index(op.f('ix_students_status'), 'students', ['status'], unique=False)
    op.create_index(op.f('ix_students_student_number'), 'students', ['student_number'], unique=True)
    op.drop_constraint(op.f('students_cohort_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'members', ['member_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('students', 'first_name')
    op.drop_column('students', 'address_line2')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'state')
    op.drop_column('students', 'phone')
    op.drop_column('students', 'postal_code')
    op.drop_column('students', 'middle_name')
    op.drop_column('students', 'city')
    op.drop_column('students', 'email')
    op.drop_column('students', 'address')
    op.drop_column('students', 'extra')
    op.drop_column('students', 'address_line1')
    op.drop_column('students', 'shoe_size')
    op.drop_column('students', 'shirt_size')
    op.drop_column('students', 'emergency_contact_relation')
    op.drop_column('students', 'profile_photo_path')
    op.drop_column('students', 'cohort_id')
    op.drop_column('students', 'birthdate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('cohort_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('profile_photo_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('emergency_contact_relation', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('shirt_size', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('shoe_size', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('address_line1', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('middle_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('address_line2', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_cohort_id_fkey'), 'students', 'cohorts', ['cohort_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_students_student_number'), table_name='students')
    op.drop_index(op.f('ix_students_status'), table_name='students')
    op.drop_index(op.f('ix_students_member_id'), table_name='students')
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_cohort_id'), 'students', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_student_name'), 'students', ['last_name', 'first_name'], unique=False)
    op.create_index(op.f('ix_student_city_state'), 'students', ['city', 'state'], unique=False)
    op.alter_column('students', 'emergency_contact_phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('students', 'emergency_contact_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('students', 'notes')
    op.drop_column('students', 'emergency_contact_relationship')
    op.drop_column('students', 'cohort')
    op.drop_column('students', 'actual_completion_date')
    op.drop_column('students', 'expected_completion_date')
    op.drop_column('students', 'enrollment_date')
    op.drop_column('students', 'application_date')
    op.drop_column('students', 'status')
    op.drop_column('students', 'student_number')
    op.drop_column('students', 'member_id')
    op.add_column('members', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('members_student_id_fkey'), 'members', 'students', ['student_id'], ['id'])
    op.add_column('class_sessions', sa.Column('instructor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('class_sessions', sa.Column('cohort_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('class_sessions', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('class_sessions', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('class_sessions', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('class_sessions', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'class_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('class_sessions_cohort_id_fkey'), 'class_sessions', 'cohorts', ['cohort_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('class_sessions_instructor_id_fkey'), 'class_sessions', 'instructors', ['instructor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('class_sessions_location_id_fkey'), 'class_sessions', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_class_sessions_session_date'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_course_id'), table_name='class_sessions')
    op.create_index(op.f('ix_class_sessions_location_id'), 'class_sessions', ['location_id'], unique=False)
    op.create_index(op.f('ix_class_sessions_is_deleted'), 'class_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_class_sessions_instructor_id'), 'class_sessions', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_class_sessions_id'), 'class_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_class_sessions_date'), 'class_sessions', ['date'], unique=False)
    op.create_index(op.f('ix_class_sessions_cohort_id'), 'class_sessions', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_class_session_date_cohort'), 'class_sessions', ['date', 'cohort_id'], unique=False)
    op.alter_column('class_sessions', 'topic',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('class_sessions', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('class_sessions', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.drop_column('class_sessions', 'cancellation_reason')
    op.drop_column('class_sessions', 'is_cancelled')
    op.drop_column('class_sessions', 'instructor_name')
    op.drop_column('class_sessions', 'room')
    op.drop_column('class_sessions', 'location')
    op.drop_column('class_sessions', 'session_date')
    op.drop_column('class_sessions', 'course_id')
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('class_session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', 'EARLY_DEPARTURE', name='attendance_status'), autoincrement=False, nullable=False),
    sa.Column('minutes_late', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], name=op.f('attendance_class_session_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('attendance_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_pkey')),
    sa.UniqueConstraint('student_id', 'class_session_id', name=op.f('uq_student_session'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.create_index(op.f('ix_attendance_status'), 'attendance', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_is_deleted'), 'attendance', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_class_session_id'), 'attendance', ['class_session_id'], unique=False)
    op.drop_index(op.f('ix_grades_student_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_course_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_status'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_certifications_student_id'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_status'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_cert_type'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_attendances_student_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_status'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_class_session_id'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_courses_is_deleted'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
