"""update cohort model for M2M instructors

Revision ID: a7f0648adb7d
Revises: 3ed3114af8c3
Create Date: 2025-11-27 03:42:54.948596

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a7f0648adb7d"
down_revision: Union[str, Sequence[str], None] = "3ed3114af8c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
