"""add instructor_cohort m2m and primary_instructor to cohorts

Revision ID: a9b228e41051
Revises: 8fc125e0b053
Create Date: 2025-11-27 03:35:05.281025

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a9b228e41051"
down_revision: Union[str, Sequence[str], None] = "8fc125e0b053"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instructor_cohort",
        sa.Column("instructor_id", sa.Integer(), nullable=False),
        sa.Column("cohort_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["cohort_id"], ["cohorts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["instructor_id"], ["instructors.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("instructor_id", "cohort_id"),
    )
    op.add_column(
        "cohorts", sa.Column("primary_instructor_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        op.f("cohorts_instructor_id_fkey"), "cohorts", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "cohorts", "instructors", ["primary_instructor_id"], ["id"]
    )
    op.drop_column("cohorts", "instructor_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cohorts",
        sa.Column("instructor_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "cohorts", type_="foreignkey")
    op.create_foreign_key(
        op.f("cohorts_instructor_id_fkey"),
        "cohorts",
        "instructors",
        ["instructor_id"],
        ["id"],
    )
    op.drop_column("cohorts", "primary_instructor_id")
    op.drop_table("instructor_cohort")
    # ### end Alembic commands ###
