"""Make requested_by_id nullable in dues_adjustments

Revision ID: ad59f152f845
Revises: ee8ead726e9b
Create Date: 2026-01-28 20:27:50.955966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad59f152f845'
down_revision: Union[str, Sequence[str], None] = 'ee8ead726e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dues_adjustments', 'requested_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dues_adjustments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'DENIED', name='adjustmentstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dues_adjustments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dues_adjustments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dues_payments', 'amount_paid',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dues_payments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'DUE', 'PARTIAL', 'PAID', 'OVERDUE', 'WAIVED', 'WRITTEN_OFF', name='duespaymentstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dues_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dues_payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dues_payments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dues_rates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dues_rates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dues_rates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('dues_rates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('dues_payments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('dues_payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('dues_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('dues_payments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'DUE', 'PARTIAL', 'PAID', 'OVERDUE', 'WAIVED', 'WRITTEN_OFF', name='duespaymentstatus'),
               server_default=sa.text("'PENDING'::duespaymentstatus"),
               existing_nullable=False)
    op.alter_column('dues_payments', 'amount_paid',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('dues_adjustments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('dues_adjustments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('dues_adjustments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'DENIED', name='adjustmentstatus'),
               server_default=sa.text("'PENDING'::adjustmentstatus"),
               existing_nullable=False)
    op.alter_column('dues_adjustments', 'requested_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
