"""add cohort_id foreign key to students

Revision ID: b22ffcf7b09f
Revises: bd9a2dbfec34
Create Date: 2025-11-27 02:26:12.681844

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b22ffcf7b09f"
down_revision: Union[str, Sequence[str], None] = "bd9a2dbfec34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("cohort_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "students", "cohorts", ["cohort_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "students", type_="foreignkey")
    op.drop_column("students", "cohort_id")
    # ### end Alembic commands ###
