"""Add Phase 2 union operations models

Revision ID: bc1f99c730dc
Revises: 0b9b93948cdb
Create Date: 2026-01-27 23:40:42.046429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc1f99c730dc'
down_revision: Union[str, Sequence[str], None] = '0b9b93948cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benevolence_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Enum('MEDICAL', 'DEATH_IN_FAMILY', 'HARDSHIP', 'DISASTER', 'OTHER', name='benevolencereason'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount_requested', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'DENIED', 'PAID', name='benevolencestatus'), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benevolence_applications_id'), 'benevolence_applications', ['id'], unique=False)
    op.create_index(op.f('ix_benevolence_applications_is_deleted'), 'benevolence_applications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_benevolence_applications_member_id'), 'benevolence_applications', ['member_id'], unique=False)
    op.create_index(op.f('ix_benevolence_applications_status'), 'benevolence_applications', ['status'], unique=False)
    op.create_table('grievances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grievance_number', sa.String(length=20), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=True),
    sa.Column('contract_article', sa.String(length=50), nullable=True),
    sa.Column('violation_description', sa.Text(), nullable=False),
    sa.Column('remedy_sought', sa.Text(), nullable=True),
    sa.Column('current_step', sa.Enum('STEP_1', 'STEP_2', 'STEP_3', 'ARBITRATION', name='grievancestep'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATION', 'HEARING', 'SETTLED', 'WITHDRAWN', 'ARBITRATION', 'CLOSED', name='grievancestatus'), nullable=False),
    sa.Column('assigned_rep', sa.String(length=100), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('settlement_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievances_employer_id'), 'grievances', ['employer_id'], unique=False)
    op.create_index(op.f('ix_grievances_grievance_number'), 'grievances', ['grievance_number'], unique=True)
    op.create_index(op.f('ix_grievances_id'), 'grievances', ['id'], unique=False)
    op.create_index(op.f('ix_grievances_is_deleted'), 'grievances', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_grievances_member_id'), 'grievances', ['member_id'], unique=False)
    op.create_index(op.f('ix_grievances_status'), 'grievances', ['status'], unique=False)
    op.create_table('salting_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('OUTREACH', 'SITE_VISIT', 'LEAFLETING', 'ONE_ON_ONE', 'MEETING', 'PETITION_DRIVE', 'CARD_SIGNING', 'INFORMATION_SESSION', 'OTHER', name='saltingactivitytype'), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('outcome', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'NO_CONTACT', name='saltingoutcome'), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('workers_contacted', sa.Integer(), nullable=True),
    sa.Column('cards_signed', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salting_activities_id'), 'salting_activities', ['id'], unique=False)
    op.create_index(op.f('ix_salting_activities_is_deleted'), 'salting_activities', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_salting_activities_member_id'), 'salting_activities', ['member_id'], unique=False)
    op.create_index(op.f('ix_salting_activities_organization_id'), 'salting_activities', ['organization_id'], unique=False)
    op.create_table('benevolence_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_name', sa.Text(), nullable=False),
    sa.Column('review_level', sa.Enum('VP', 'ADMIN', 'MANAGER', 'PRESIDENT', name='benevolencereviewlevel'), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'DENIED', 'NEEDS_INFO', 'DEFERRED', name='benevolencereviewdecision'), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['benevolence_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benevolence_reviews_application_id'), 'benevolence_reviews', ['application_id'], unique=False)
    op.create_index(op.f('ix_benevolence_reviews_id'), 'benevolence_reviews', ['id'], unique=False)
    op.create_table('grievance_step_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grievance_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('union_attendees', sa.Text(), nullable=True),
    sa.Column('employer_attendees', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('DENIED', 'SETTLED', 'ADVANCED', name='grievancestepoutcome'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievance_step_records_grievance_id'), 'grievance_step_records', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_grievance_step_records_id'), 'grievance_step_records', ['id'], unique=False)
    # NOTE: Existing production indexes (idx_member_employments_*, idx_members_*, idx_contacts_*, idx_organization_contacts_*)
    # are intentionally preserved - they were created in migration 0b9b93948cdb and should NOT be dropped.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grievance_step_records_id'), table_name='grievance_step_records')
    op.drop_index(op.f('ix_grievance_step_records_grievance_id'), table_name='grievance_step_records')
    op.drop_table('grievance_step_records')
    op.drop_index(op.f('ix_benevolence_reviews_id'), table_name='benevolence_reviews')
    op.drop_index(op.f('ix_benevolence_reviews_application_id'), table_name='benevolence_reviews')
    op.drop_table('benevolence_reviews')
    op.drop_index(op.f('ix_salting_activities_organization_id'), table_name='salting_activities')
    op.drop_index(op.f('ix_salting_activities_member_id'), table_name='salting_activities')
    op.drop_index(op.f('ix_salting_activities_is_deleted'), table_name='salting_activities')
    op.drop_index(op.f('ix_salting_activities_id'), table_name='salting_activities')
    op.drop_table('salting_activities')
    op.drop_index(op.f('ix_grievances_status'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_member_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_is_deleted'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_grievance_number'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_employer_id'), table_name='grievances')
    op.drop_table('grievances')
    op.drop_index(op.f('ix_benevolence_applications_status'), table_name='benevolence_applications')
    op.drop_index(op.f('ix_benevolence_applications_member_id'), table_name='benevolence_applications')
    op.drop_index(op.f('ix_benevolence_applications_is_deleted'), table_name='benevolence_applications')
    op.drop_index(op.f('ix_benevolence_applications_id'), table_name='benevolence_applications')
    op.drop_table('benevolence_applications')
    # ### end Alembic commands ###
