"""add date_issued to tools_issued

Revision ID: c8997d54c438
Revises: 48c5009efd3d
Create Date: 2025-11-27 04:07:01.187445

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c8997d54c438"
down_revision: Union[str, Sequence[str], None] = "48c5009efd3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tools_issued", sa.Column("date_issued", sa.Date(), nullable=False))
    op.drop_column("tools_issued", "issued_date")
    op.drop_column("tools_issued", "cost")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tools_issued",
        sa.Column(
            "cost",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "tools_issued",
        sa.Column("issued_date", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.drop_column("tools_issued", "date_issued")
    # ### end Alembic commands ###
