"""add grant_id FK to expenses

Revision ID: e1e6f2e3b927
Revises: 4653519832ea
Create Date: 2025-11-27 03:02:14.435832

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1e6f2e3b927"
down_revision: Union[str, Sequence[str], None] = "4653519832ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expenses", sa.Column("grant_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "expenses", "grants", ["grant_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "expenses", type_="foreignkey")
    op.drop_column("expenses", "grant_id")
    # ### end Alembic commands ###
