"""Add auth models: User, Role, UserRole, RefreshToken

Revision ID: e382f497c5e3
Revises: 6f77d764d2c3
Create Date: 2026-01-28 07:01:58.870266

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e382f497c5e3"
down_revision: Union[str, Sequence[str], None] = "6f77d764d2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_system_role", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("device_info", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "user_roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("assigned_by", sa.String(length=255), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", name="uq_user_role"),
    )
    op.create_index(
        op.f("ix_user_roles_role_id"), "user_roles", ["role_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False
    )
    op.drop_index(op.f("idx_member_employments_dates"), table_name="member_employments")
    op.drop_index(
        op.f("idx_member_employments_member_id"), table_name="member_employments"
    )
    op.drop_index(
        op.f("idx_member_employments_organization_id"), table_name="member_employments"
    )
    op.drop_index(
        op.f("idx_members_active"),
        table_name="members",
        postgresql_where="(status = 'ACTIVE'::memberstatus)",
    )
    op.drop_index(op.f("idx_members_status_classification"), table_name="members")
    op.drop_index(
        op.f("idx_contacts_primary"),
        table_name="organization_contacts",
        postgresql_where="(is_primary = true)",
    )
    op.drop_index(
        op.f("idx_organization_contacts_org_id"), table_name="organization_contacts"
    )
    op.add_column(
        "users", sa.Column("last_login", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("users", sa.Column("member_id", sa.Integer(), nullable=True))
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "users",
        "first_name",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "locked_until",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_user_role_active"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_instructor_id"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_student_id"), table_name="users")
    op.create_unique_constraint(None, "users", ["member_id"])
    op.create_foreign_key(
        None, "users", "members", ["member_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("users", "role")
    op.drop_column("users", "last_login_at")
    op.drop_column("users", "instructor_id")
    op.drop_column("users", "student_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("student_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("instructor_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "last_login_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column("role", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="unique")
    op.create_index(op.f("ix_users_student_id"), "users", ["student_id"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(
        op.f("ix_users_instructor_id"), "users", ["instructor_id"], unique=False
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_role_active"), "users", ["role", "is_active"], unique=False
    )
    op.alter_column(
        "users",
        "locked_until",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "first_name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_column("users", "member_id")
    op.drop_column("users", "last_login")
    op.create_index(
        op.f("idx_organization_contacts_org_id"),
        "organization_contacts",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_contacts_primary"),
        "organization_contacts",
        ["organization_id"],
        unique=False,
        postgresql_where="(is_primary = true)",
    )
    op.create_index(
        op.f("idx_members_status_classification"),
        "members",
        ["status", "classification"],
        unique=False,
    )
    op.create_index(
        op.f("idx_members_active"),
        "members",
        ["status"],
        unique=False,
        postgresql_where="(status = 'ACTIVE'::memberstatus)",
    )
    op.create_index(
        op.f("idx_member_employments_organization_id"),
        "member_employments",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_member_employments_member_id"),
        "member_employments",
        ["member_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_member_employments_dates"),
        "member_employments",
        ["start_date", "end_date"],
        unique=False,
    )
    op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_role_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_table("roles")
    # ### end Alembic commands ###
