"""add instructor_hours table

Revision ID: f307d39a8205
Revises: c2e76c575cc3
Create Date: 2025-11-27 02:43:08.695256

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f307d39a8205"
down_revision: Union[str, Sequence[str], None] = "c2e76c575cc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instructor_hours",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instructor_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("cohort_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("hours", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("prep_hours", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("total_hours", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cohort_id"],
            ["cohorts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instructor_id"],
            ["instructors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_instructor_hours_id"), "instructor_hours", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_instructor_hours_id"), table_name="instructor_hours")
    op.drop_table("instructor_hours")
    # ### end Alembic commands ###
