"""Service functions for User model."""

from typing import Optional

from sqlalchemy import select
from sqlalchemy.orm import Session

from src.models.user import User
from src.schemas.user import UserCreate, UserUpdate


def get_user(db: Session, user_id: int) -> Optional[User]:
    """Get a user by ID."""
    return db.get(User, user_id)


def get_user_by_email(db: Session, email: str) -> Optional[User]:
    """Get a user by email address."""
    stmt = select(User).where(User.email == email)
    return db.execute(stmt).scalar_one_or_none()


def get_users(
    db: Session, skip: int = 0, limit: int = 100, include_inactive: bool = False
) -> list[User]:
    """Get a list of users."""
    stmt = select(User)
    if not include_inactive:
        stmt = stmt.where(User.is_active)
    stmt = stmt.offset(skip).limit(limit)
    return list(db.execute(stmt).scalars().all())


def create_user(db: Session, user_data: UserCreate, password_hash: str) -> User:
    """
    Create a new user.

    Note: password_hash should be generated by the auth layer,
    not stored as plaintext from user_data.password.
    """
    user = User(
        email=user_data.email,
        first_name=user_data.first_name,
        last_name=user_data.last_name,
        password_hash=password_hash,
        member_id=user_data.member_id,
    )
    db.add(user)
    db.commit()
    db.refresh(user)
    return user


def update_user(db: Session, user: User, user_data: UserUpdate) -> User:
    """Update an existing user."""
    update_data = user_data.model_dump(exclude_unset=True)
    for field, value in update_data.items():
        setattr(user, field, value)
    db.commit()
    db.refresh(user)
    return user


def delete_user(db: Session, user: User) -> None:
    """Soft delete a user."""
    user.soft_delete()
    db.commit()


def verify_user(db: Session, user: User) -> User:
    """Mark user as verified."""
    user.is_verified = True
    db.commit()
    db.refresh(user)
    return user
