# src/scripts/new_migration.py
from __future__ import annotations

import argparse
import datetime as dt
import re
import subprocess
import sys
from pathlib import Path

MIGRATIONS_DIR = Path("src/db/migrations/versions")  # adjust if yours differs
SLUG_RE = re.compile(r"[^a-z0-9]+")


def slugify(msg: str) -> str:
    s = msg.strip().lower()
    s = SLUG_RE.sub("_", s).strip("_")
    return s or "migration"


def utc_timestamp() -> str:
    # Use UTC to avoid timezone-related filename ordering weirdness
    return dt.datetime.utcnow().strftime("%Y%m%d%H%M%S")


HEADER = """\"\"\"{title}

Governance:
- Generated by: src/scripts/new_migration.py
- New migrations must be timestamped: YYYYMMDDHHMMSS_description.py
- If this migration contains *intentional* breaking changes in upgrade(),
  add: # BREAKING_OK (and explain why in a comment)

\"\"\"
"""


def latest_migration_file() -> Path | None:
    if not MIGRATIONS_DIR.exists():
        return None
    files = sorted(
        MIGRATIONS_DIR.glob("*.py"), key=lambda p: p.stat().st_mtime, reverse=True
    )
    return files[0] if files else None


def inject_header(path: Path, title: str) -> None:
    text = path.read_text(encoding="utf-8")
    # Alembic creates a module docstring already; we’ll replace it safely if present.
    # If no docstring, we’ll prepend.
    if text.lstrip().startswith('"""') or text.lstrip().startswith("'''"):
        # Replace first docstring block
        quote = '"""' if '"""' in text[:10] else "'''"
        parts = text.split(quote, 2)
        if len(parts) >= 3:
            new_text = parts[0] + HEADER.format(title=title) + quote + parts[2]
        else:
            new_text = HEADER.format(title=title) + text
    else:
        new_text = HEADER.format(title=title) + text

    path.write_text(new_text, encoding="utf-8")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Create a governed Alembic migration.")
    parser.add_argument(
        "-m",
        "--message",
        required=True,
        help="Migration message, e.g. 'add student status'",
    )
    parser.add_argument(
        "--autogenerate", action="store_true", help="Run Alembic autogenerate"
    )
    args = parser.parse_args(argv)

    if not MIGRATIONS_DIR.exists():
        print(f"ERROR: migrations dir not found: {MIGRATIONS_DIR}", file=sys.stderr)
        return 2

    ts = utc_timestamp()
    slug = slugify(args.message)
    target_name = f"{ts}_{slug}.py"
    title = f"{ts} - {args.message.strip()}"

    before = latest_migration_file()

    cmd = ["alembic", "revision", "-m", args.message]
    if args.autogenerate:
        cmd.append("--autogenerate")

    print("Running:", " ".join(cmd))
    p = subprocess.run(cmd, check=False)
    if p.returncode != 0:
        return p.returncode

    after = latest_migration_file()
    if after is None or after == before:
        print("ERROR: could not detect newly created migration file.", file=sys.stderr)
        return 3

    target_path = MIGRATIONS_DIR / target_name
    after.rename(target_path)
    inject_header(target_path, title=title)

    print(f"✅ Created governed migration: {target_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
