"""add capacity to location table

Revision ID: 48c5009efd3d
Revises: a7f0648adb7d
Create Date: 2025-11-27 03:58:29.996504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c5009efd3d'
down_revision: Union[str, Sequence[str], None] = 'a7f0648adb7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('capacity', sa.Integer(), nullable=True))
    op.alter_column('locations', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('locations', 'zip_code')
    op.drop_column('locations', 'state')
    op.drop_column('locations', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('zip_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('locations', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('locations', 'capacity')
    # ### end Alembic commands ###
